### ISSUE TITLE
Mecab 동작 안되는 원인 확인해야함. 

### ISSUE THREAD

**Issue by YongwoonJang** [YongwoonJang/gyujanggak#1]
❯ docker container run -it --name app app
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/konlpy/tag/_mecab.py", line 108, in __init__
    self.tagger = Tagger('-d %s' % dicpath)
NameError: name 'Tagger' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gyujanggak.py", line 10, in <module>
    mecab = Mecab()
  File "/usr/local/lib/python3.7/site-packages/konlpy/tag/_mecab.py", line 113, in __init__
    raise Exception('Install MeCab in order to use it: http://konlpy.org/en/latest/install/')
Exception: Install MeCab in order to use it: http://konlpy.org/en/latest/install/

**Comment by YongwoonJang** [comment]
그냥 신경쓰기 않고, 아래와 같이 Dockerfile 만들어서 사용하기로 했음. 

이하는 Dockerfile 내용임. 
> FROM python:3
> ENV JAVA_HOME /usr/lib/jvm/java-1.7-openjdk/jre
> RUN apt-get update && apt-get install -y g++ default-jdk
> RUN pip install konlpy

출처 : https://konlpy.org/en/latest/install/
